// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BigScreen: typeof import('./src/components/bigScreen/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VAppBarTitle: typeof import('vuetify/lib')['VAppBarTitle']
    VBadge: typeof import('vuetify/lib')['VBadge']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFadeTransition: typeof import('vuetify/lib')['VFadeTransition']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemActionText: typeof import('vuetify/lib')['VListItemActionText']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemGroup: typeof import('vuetify/lib')['VListItemGroup']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VOverlay: typeof import('vuetify/lib')['VOverlay']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VProgressLinear: typeof import('vuetify/lib')['VProgressLinear']
    VRow: typeof import('vuetify/lib')['VRow']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    Warning: typeof import('./src/components/warning.vue')['default']
  }
}
